import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Link from "next/link";
import { Layout, Menu } from "antd";
import { Header } from "antd/es/layout/layout";
import { Content } from "antd/es/layout/layout";

const items = [
	{
		key: 0,
		label: <Link href="/home">Home</Link>,
	},
	{
		key: 1,
		label: <Link href="./albums">Albums</Link>,
	},

	{
		key: 2,
		label: <Link href="./posts">Post</Link>,
	},
	{
		key: 3,
		label: <Link href="./todos">Todo</Link>,
	},
];
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AntdRegistry>
					<Layout>
						<Header>
							<Menu
								theme="dark"
								mode="horizontal"
								defaultSelectedKeys={["0"]}
								items={items}
								style={{ flex: 1, minWidth: 0 }}
							/>
						</Header>
						<Content>{children}</Content>
					</Layout>
				</AntdRegistry>
			</body>
		</html>
	);
}
